{
 "title": "Calendar",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "gRPC [Latency]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_grpc_stats_sum[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC [RPC]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_grpc_stats_count[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "gRPC [Codes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(calendar_grpc_Codes[1m])", "legendFormat": "{{method}}:{{code}}" }
   ]
  },
  {
   "title": "REST [Latency]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_http_stats_sum[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "REST [RPC]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_http_stats_count[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "REST [Codes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(calendar_http_Codes[1m])", "legendFormat": "{{method}}:{{code}}" }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "description": "count events in database",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_stat_user_count_cnt", "legendFormat": "pg_stat_cnt" },
    { "expr": "calendar_events_count_cnt", "legendFormat": "active events" },
    {
     "expr": "calendar_events_count_full_full_cnt",
     "legendFormat": "full events"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"calendar\"}[1m])",
     "legendFormat": "commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"calendar\"}[1m])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"calendar\"}",
     "legendFormat": "{{job}}-{{state}}"
    }
   ]
  },
  {
   "title": "Notice",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(calendar_notifier_sender[1m])"
    }
   ]
  }
 ]
}