http_listen:
  ip: "0.0.0.0"
  port: 2000
grpc:
  host: "localhost"
  port: 5001
log:
  log_file: application.log
  log_level: debug
db:
  user: root
  password: password
  host: "calendar-db"
  port: 5432
  database: calendar
ampq:
  host: "calendar-rabbit"
  port: 5672
  user: root
  password: password
scheduler:
  period: 60
  before_time: 60
  event_time: 60
