http_listen:
  ip: "0.0.0.0"
  port: 2000
grpc:
  host: "localhost"
  port: 5001
log:
  log_file: ../cmd/application.log
  log_level: debug
db:
  user: root
  password: password
  host: localhost
  port: 5435
  database: calendar
